name = input("Enter your name :")
roll = input("Enter your roll :")
student_class = input("Enter your class :")
city = input("Enter your city :")
subject = input("Enter you sub :")

print("--------------")
print("    Name :",name)
print(" Roll No :",roll)
print("    city :",city)
print("  subject:",subject)