var express = require("express");
var router = express.Router();

// user json

const user = [
  {
    id: 1,
    name: "Alice Johnson",
    username: "alicej",
    email: "alice.johnson@example.com",
    phone: "+91-9876543210",
    website: "alice.dev",
    company: "TechNova",
    address: {
      city: "Mumbai",
      street: "Link Road",
      zipcode: "400001",
    },
    role: "Frontend Developer",
  },
  {
    id: 2,
    name: "Michael Smith",
    username: "mikesmith",
    email: "michael.smith@example.com",
    phone: "+91-9123456780",
    website: "mikebackend.com",
    company: "CodeCraft",
    address: {
      city: "Delhi",
      street: "MG Road",
      zipcode: "110001",
    },
    role: "Backend Engineer",
  },
  {
    id: 3,
    name: "Sophia Williams",
    username: "sophiaw",
    email: "sophia.w@example.com",
    phone: "+91-9988776655",
    website: "sophiaPM.com",
    company: "AgileWorks",
    address: {
      city: "Bangalore",
      street: "Brigade Road",
      zipcode: "560001",
    },
    role: "Project Manager",
  },
  {
    id: 4,
    name: "Daniel Martinez",
    username: "danielux",
    email: "daniel.m@example.com",
    phone: "+91-9090909090",
    website: "danieldesign.com",
    company: "DesignHub",
    address: {
      city: "Pune",
      street: "FC Road",
      zipcode: "411001",
    },
    role: "UI/UX Designer",
  },
  {
    id: 5,
    name: "Emma Davis",
    username: "emmafull",
    email: "emma.d@example.com",
    phone: "+91-8888888888",
    website: "emmacode.com",
    company: "StackFlow",
    address: {
      city: "Hyderabad",
      street: "Hitech City",
      zipcode: "500081",
    },
    role: "Full Stack Developer",
  },

  {
    id: 6,
    name: "James Miller",
    username: "jamestest",
    email: "james.m@example.com",
    phone: "+91-7777777777",
    website: "qatest.com",
    company: "TestPro",
    address: {
      city: "Chennai",
      street: "Anna Salai",
      zipcode: "600001",
    },
    role: "QA Engineer",
  },
  {
    id: 7,
    name: "Olivia Brown",
    username: "oliviadata",
    email: "olivia.b@example.com",
    phone: "+91-6666666666",
    website: "datainsight.com",
    company: "DataMind",
    address: {
      city: "Ahmedabad",
      street: "CG Road",
      zipcode: "380001",
    },
    role: "Data Analyst",
  },
  {
    id: 8,
    name: "Henry Wilson",
    username: "henrydevops",
    email: "henry.w@example.com",
    phone: "+91-5555555555",
    website: "cloudops.com",
    company: "CloudNet",
    address: {
      city: "Jaipur",
      street: "MI Road",
      zipcode: "302001",
    },
    role: "DevOps Engineer",
  },
  {
    id: 9,
    name: "Ava Thompson",
    username: "avasec",
    email: "ava.t@example.com",
    phone: "+91-4444444444",
    website: "secureweb.com",
    company: "SecureIT",
    address: {
      city: "Kolkata",
      street: "Park Street",
      zipcode: "700001",
    },
    role: "Security Specialist",
  },
  {
    id: 10,
    name: "Lucas Anderson",
    username: "lucasmobile",
    email: "lucas.a@example.com",
    phone: "+91-3333333333",
    website: "mobileapps.com",
    company: "AppWorld",
    address: {
      city: "Surat",
      street: "Ring Road",
      zipcode: "395002",
    },
    role: "Mobile Developer",
  },

  {
    id: 11,
    name: "Ethan Clark",
    username: "ethanai",
    email: "ethan.c@example.com",
    phone: "+91-2222222222",
    website: "aiworld.com",
    company: "AI Labs",
    address: {
      city: "Noida",
      street: "Sector 62",
      zipcode: "201301",
    },
    role: "AI Engineer",
  },
  {
    id: 12,
    name: "Mia Rodriguez",
    username: "miaba",
    email: "mia.r@example.com",
    phone: "+91-1111111111",
    website: "bizanalysis.com",
    company: "BizTech",
    address: {
      city: "Indore",
      street: "Vijay Nagar",
      zipcode: "452010",
    },
    role: "Business Analyst",
  },

  {
    id: 13,
    name: "Noah Lewis",
    username: "noahcloud",
    email: "noah.l@example.com",
    phone: "+91-9999991111",
    website: "cloudmaster.com",
    company: "SkyCloud",
    address: {
      city: "Nagpur",
      street: "Sitabuldi",
      zipcode: "440001",
    },
    role: "Cloud Architect",
  },
  {
    id: 14,
    name: "Isabella Walker",
    username: "isahr",
    email: "isa.w@example.com",
    phone: "+91-8888777766",
    website: "hrworld.com",
    company: "PeopleFirst",
    address: {
      city: "Bhopal",
      street: "MP Nagar",
      zipcode: "462011",
    },
    role: "HR Manager",
  },
  {
    id: 15,
    name: "William Hall",
    username: "willdb",
    email: "will.h@example.com",
    phone: "+91-7777666655",
    website: "dbadmin.com",
    company: "DataCore",
    address: {
      city: "Lucknow",
      street: "Hazratganj",
      zipcode: "226001",
    },
    role: "Database Administrator",
  },

  {
    id: 16,
    name: "Charlotte Allen",
    username: "charlottewrite",
    email: "charlotte.a@example.com",
    phone: "+91-6666555544",
    website: "contentpro.com",
    company: "WriteHub",
    address: {
      city: "Chandigarh",
      street: "Sector 17",
      zipcode: "160017",
    },
    role: "Content Writer",
  },
  {
    id: 17,
    name: "Benjamin Young",
    username: "bengame",
    email: "ben.y@example.com",
    phone: "+91-5555444433",
    website: "gamedev.com",
    company: "GameZone",
    address: {
      city: "Goa",
      street: "Panaji",
      zipcode: "403001",
    },
    role: "Game Developer",
  },
  {
    id: 18,
    name: "Amelia Hernandez",
    username: "ameliamkt",
    email: "amelia.h@example.com",
    phone: "+91-4444333322",
    website: "digitalads.com",
    company: "AdBoost",
    address: {
      city: "Kochi",
      street: "MG Road",
      zipcode: "682016",
    },
    role: "Digital Marketer",
  },
  {
    id: 19,
    name: "Elijah King",
    username: "elijahsys",
    email: "elijah.k@example.com",
    phone: "+91-3333222211",
    website: "systempro.com",
    company: "InfraTech",
    address: {
      city: "Patna",
      street: "Boring Road",
      zipcode: "800001",
    },
    role: "System Engineer",
  },
  {
    id: 20,
    name: "Harper Scott",
    username: "harperdesign",
    email: "harper.s@example.com",
    phone: "+91-2222111100",
    website: "graphicspro.com",
    company: "Designify",
    address: {
      city: "Ranchi",
      street: "Main Road",
      zipcode: "834001",
    },
    role: "Graphic Designer",
  },
];

/* GET users listing. */
router.get("/", function (req, res) {
  res.json(user);
});

module.exports = router;
